# Site settings
title: Coding Blog
header-img: img/home-bg.png
email: cdhenry@gmail.com
copyright_name: cdhenry
description: > # this means to ignore newlines until "baseurl:"
  An Educational Blog for The Flatiron School
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  cdhenry
learn_profile: cdhenry
email_username: cdhenry@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
